# Generated by Django 4.2.3 on 2025-09-20 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_prompt",
                    models.TextField(
                        default="",
                        help_text="Original user prompt for course generation",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(default="Beginner", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_chapters", models.IntegerField(default=0)),
                ("total_lessons", models.IntegerField(default=0)),
                (
                    "course_data_json",
                    models.JSONField(
                        blank=True,
                        help_text="Complete course structure as JSON",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_number", models.IntegerField()),
                ("chapter_name", models.CharField(max_length=200)),
                ("chapter_description", models.TextField()),
                (
                    "difficulty_rating",
                    models.IntegerField(default=-1, help_text="Difficulty from 1-10"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="generation.coursegeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter_number"],
                "unique_together": {("course_generation", "chapter_number")},
            },
        ),
        migrations.CreateModel(
            name="LessonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("type_id", models.IntegerField(unique=True)),
                ("display_name", models.CharField(default="", max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["type_id"],
            },
        ),
        migrations.CreateModel(
            name="GenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        help_text="Which step in the generation process", max_length=100
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        help_text="Additional data for this log entry",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="generation.coursegeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_number", models.IntegerField()),
                ("lesson_type", models.CharField(max_length=50)),
                ("lesson_type_id", models.IntegerField(blank=True, null=True)),
                ("lesson_name", models.CharField(max_length=200)),
                ("lesson_description", models.TextField()),
                ("lesson_details", models.TextField()),
                ("lesson_goals", models.TextField(help_text="Learning objectives")),
                (
                    "lesson_guidelines",
                    models.TextField(
                        blank=True, help_text="Guidelines for creating the lesson"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="generation.generatedchapter",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson_number"],
                "unique_together": {("chapter", "lesson_number")},
            },
        ),
    ]
