# Generated by Django 4.2.3 on 2025-09-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleChoiceQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quiz_data",
                    models.JSONField(
                        help_text="Quiz questions, options, and answers in JSON format"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="generation.generatedlesson",
                    ),
                ),
            ],
        ),
    ]
