# Generated by Django 4.2.3 on 2025-09-20 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("generation", "0002_multiplechoicequiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(
                        help_text="User's answers to quiz questions in JSON format"
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        help_text="Results showing which answers were correct/incorrect"
                    ),
                ),
                ("score", models.IntegerField(help_text="Number of correct answers")),
                (
                    "total_questions",
                    models.IntegerField(help_text="Total number of questions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="generation.multiplechoicequiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
