# Generated by Django 5.2.6 on 2025-09-20 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0003_quizattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Generated article content")),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article",
                        to="generation.generatedlesson",
                    ),
                ),
            ],
        ),
    ]
