# Generated by Django 5.2.6 on 2025-09-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0004_articlecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("channel_title", models.CharField(blank=True, max_length=200)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="youtube_videos",
                        to="generation.generatedlesson",
                    ),
                ),
            ],
        ),
    ]
