# Generated by Django 5.2.6 on 2025-09-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0005_youtubevideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "starter_files",
                    models.JSONField(
                        help_text="Dictionary of filename to starter code content"
                    ),
                ),
                (
                    "grading_method",
                    models.CharField(
                        choices=[
                            ("ai_review", "AI Review"),
                            ("terminal_matching", "Terminal Matching"),
                        ],
                        default="ai_review",
                        max_length=20,
                    ),
                ),
                (
                    "expected_output",
                    models.TextField(
                        blank=True, help_text="Expected terminal output for grading"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project",
                        to="generation.generatedlesson",
                    ),
                ),
            ],
        ),
    ]
