# Generated by Django 5.2.6 on 2025-09-20 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0006_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalArticles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(help_text="URL of the external article")),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_article",
                        to="generation.generatedlesson",
                    ),
                ),
            ],
        ),
    ]
