# Generated by Django 5.2.6 on 2025-09-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0007_externalarticles"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessontype",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
