# Generated by Django 5.2.6 on 2025-09-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0008_lessontype_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlesson",
            name="text_questions",
            field=models.JSONField(
                blank=True,
                help_text="Text response questions and optimal answers in JSON format",
                null=True,
            ),
        ),
    ]
