# Generated by Django 5.2.6 on 2025-09-21 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0009_generatedlesson_text_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedlesson",
            name="text_questions",
        ),
        migrations.CreateModel(
            name="TextResponseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_number",
                    models.IntegerField(help_text="Question number within the lesson"),
                ),
                ("question", models.TextField(help_text="The question text")),
                (
                    "optimal_answer",
                    models.TextField(help_text="The optimal answer for this question"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_response_questions",
                        to="generation.generatedlesson",
                    ),
                ),
            ],
            options={
                "ordering": ["question_number"],
                "unique_together": {("lesson", "question_number")},
            },
        ),
    ]
