# Generated by Django 5.2.6 on 2025-09-21 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0010_remove_generatedlesson_text_questions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TextResponseSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answers",
                    models.JSONField(
                        help_text="User's answers to all questions in JSON format"
                    ),
                ),
                (
                    "grades",
                    models.JSONField(
                        help_text="Grades and feedback for each question in JSON format"
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(help_text="Overall score as percentage (0-100)"),
                ),
                (
                    "total_questions",
                    models.IntegerField(help_text="Total number of questions answered"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_submissions",
                        to="generation.generatedlesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
