# Generated by Django 5.2.6 on 2025-09-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generation", "0011_textresponsesubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedlesson",
            name="is_complete",
            field=models.BooleanField(
                default=False, help_text="Whether the learner has completed this lesson"
            ),
        ),
    ]
