# Generated by Django 5.2.6 on 2025-09-20 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("generation", "0007_externalarticles"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="expected_output",
            field=models.TextField(
                blank=True, help_text="Expected terminal output for grading"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="grading_method",
            field=models.CharField(
                choices=[
                    ("ai_review", "AI Review"),
                    ("terminal_matching", "Terminal Matching"),
                ],
                default="ai_review",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="lesson",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programming_project",
                to="generation.generatedlesson",
            ),
        ),
    ]
