# Generated by Django 5.2.6 on 2025-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_project_expected_output_project_grading_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_final_project",
            field=models.BooleanField(default=False),
        ),
    ]
